/**
 * Idempotency tests for `POST /api/generate-program`.
 *
 * Two layers:
 *  1. Pure contract tests (no DB): Idempotency-Key format validation and the
 *     deterministic request-body hash.
 *  2. State-machine tests against a REAL scratch SQLite database (created in a
 *     temp dir via `prisma db push`): success → exact retry replay, concurrent
 *     duplicates, key-reuse conflicts, failed-attempt retry, and stale-lock
 *     reclaim. Verifies the core guarantee: retries and duplicates never
 *     persist a second program.
 *
 * No secrets, no real user data. Runs offline (`db push` against a local file).
 */
import assert from 'node:assert/strict';
import {after, before, test} from 'node:test';
import {execFileSync} from 'node:child_process';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PrismaClient} from '@prisma/client';

import {isValidIdempotencyKey, requestHashOf} from '../src/lib/ai/idempotency';
import {GENERATE_PROGRAM_INPUT_SCHEMA} from '../src/lib/ai/requestSecurity';
import type {SaveGeneratedProgramInput} from '../src/services/programService';

// ---------------------------------------------------------------------------
// Scratch database setup
// ---------------------------------------------------------------------------

const tmpDir = mkdtempSync(join(tmpdir(), 'idempotency-test-'));
const dbUrl = `file:${join(tmpDir, 'idempotency-test.db')}`;

// Must be set BEFORE any module that constructs a PrismaClient is imported
// (the shared singleton in src/lib/prisma is only reached via dynamic imports
// below, which run inside `before`).
process.env.DATABASE_URL = dbUrl;

let client: PrismaClient;
let services: typeof import('../src/services/generationIdempotency');
let programService: typeof import('../src/services/programService');
let userId: string;

before(async () => {
  const prismaCli = join(process.cwd(), 'node_modules', 'prisma', 'build', 'index.js');
  execFileSync(process.execPath, [prismaCli, 'db', 'push', '--skip-generate'], {
    env: {...process.env, DATABASE_URL: dbUrl},
    stdio: 'pipe',
    timeout: 60_000,
  });

  services = await import('../src/services/generationIdempotency');
  programService = await import('../src/services/programService');
  client = new PrismaClient();

  const user = await client.user.create({
    data: {
      email: `idem-${Date.now()}@test.local`,
      name: 'Idempotency Tester',
      passwordHash: 'test-only',
    },
  });
  userId = user.id;
});

after(async () => {
  await client?.$disconnect();
  rmSync(tmpDir, {recursive: true, force: true});
});

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** A valid generation-profile body (as validated by the route's Zod schema). */
function profile(goal: 'strength' | 'fat_loss'): {
  level: string;
  goal: string;
  equipment: string[];
  limitations: string[];
  limitationsDetails: string;
} {
  return {level: 'beginner', goal, equipment: ['dumbbells', 'bench'], limitations: [], limitationsDetails: ''};
}

/** A minimal, schema-conformant AI program output. */
function sampleProgram(programId: string): SaveGeneratedProgramInput['program'] {
  return {
    mode: 'general',
    program_id: programId,
    method_mix: {
      strength_pct: 40,
      hypertrophy_pct: 20,
      cardio_pct: 15,
      mobility_pct: 10,
      pilates_pct: 0,
      bodyweight_pct: 15,
      isometric_pct: 0,
    },
    weekly_schedule: [
      {
        day: 1,
        focus: 'Full body',
        warmup: [{name: 'Jumping jacks', duration_seconds: 120, purpose: 'warm up'}],
        exercises: [
          {
            id: 'ex_1',
            name: 'Goblet Squat',
            method: 'strength',
            equipment: 'dumbbell',
            sets: 3,
            reps: '8-10',
            rest_seconds: 90,
            tempo: '2-0-2',
            rpe: 7,
            instruction_cue: 'Keep your chest up and sit between your heels.',
            alternatives: [],
            contraindicated_for: [],
          },
        ],
        cooldown: [{name: 'Quad stretch', duration_seconds: 60, purpose: 'cool down'}],
        notes: 'Focus on control.',
      },
    ],
    progression_plan: {
      weeks_1_2: 'x',
      weeks_3_5: 'y',
      week_6: 'z',
      overload_variables: ['sets'],
    },
    warnings: [],
    notes: 'Generated by tests.',
    disclaimer: 'Test disclaimer.',
  };
}

function claimedId(outcome: {kind: string} & {record?: {id: string}}): string {
  if (outcome.kind !== 'claimed' || !outcome.record) assert.fail('expected a claimed key');
  return outcome.record.id;
}

// ---------------------------------------------------------------------------
// 1. Pure contract tests (no database)
// ---------------------------------------------------------------------------

test('validates the Idempotency-Key contract', () => {
  assert.equal(isValidIdempotencyKey('abcDEF123-xyz_9'), true);
  assert.equal(isValidIdempotencyKey('12345678'), true);
  assert.equal(isValidIdempotencyKey('a'.repeat(64)), true);

  assert.equal(isValidIdempotencyKey('a'.repeat(65)), false); // too long
  assert.equal(isValidIdempotencyKey('short'), false); // below min length
  assert.equal(isValidIdempotencyKey(''), false);
  assert.equal(isValidIdempotencyKey('has space'), false);
  assert.equal(isValidIdempotencyKey('slash/name'), false);
  assert.equal(isValidIdempotencyKey(null), false);
  assert.equal(isValidIdempotencyKey(undefined), false);
});

test('request hashes are deterministic and key-order independent', () => {
  const bodyA = {level: 'beginner', goal: 'strength', equipment: ['dumbbells', 'bench'], limitations: [], limitationsDetails: ''};
  // Same content, different insertion order → identical hash (object keys are
  // canonicalized; array order is preserved as part of the payload).
  const bodyB = {limitationsDetails: '', limitations: [], goal: 'strength', equipment: ['dumbbells', 'bench'], level: 'beginner'};
  // Different goal → different hash.
  const bodyC = {level: 'beginner', goal: 'fat_loss', equipment: ['dumbbells', 'bench'], limitations: [], limitationsDetails: ''};

  assert.equal(requestHashOf(bodyA), requestHashOf(bodyB));
  assert.equal(requestHashOf(bodyA), requestHashOf({...bodyA}));
  assert.notEqual(requestHashOf(bodyA), requestHashOf(bodyC));
  assert.match(requestHashOf(bodyA), /^[0-9a-f]{64}$/);
});

test('the generation profile fixture passes the route input schema', () => {
  assert.equal(GENERATE_PROGRAM_INPUT_SCHEMA.safeParse(profile('strength')).success, true);
});

// ---------------------------------------------------------------------------
// 2. State-machine tests (real scratch SQLite database)
// ---------------------------------------------------------------------------

test('success + retry: the same key replays the exact same result without duplicate persistence', async () => {
  const key = `key-success-${Date.now()}`;
  const body = profile('strength');

  const first = await services.beginIdempotentGeneration(userId, key, body, {client});
  const recordId = claimedId(first);

  const program = await programService.persistProgramForUserWithIdempotency(
    userId,
    {program: sampleProgram('prog-success'), level: 'beginner', goal: 'strength', idempotencyRecordId: recordId},
    client,
  );

  // The record is finalized atomically with the program create.
  const record = await client.programGenerationRequest.findUniqueOrThrow({
    where: {userId_idempotencyKey: {userId, idempotencyKey: key}},
  });
  assert.equal(record.status, 'SUCCEEDED');
  assert.equal(record.programId, program.id);

  // Retry → replay of the exact 200 body, no second Program row.
  const retry = await services.beginIdempotentGeneration(userId, key, body, {client});
  assert.equal(retry.kind, 'replay');
  if (retry.kind === 'replay') {
    const payload = retry.responsePayload as {
      program: {id: string; name: string; ownerId: string};
      generated: {program_id: string};
    };
    assert.equal(payload.program.id, program.id);
    assert.equal(payload.program.name, program.name);
    assert.equal(payload.program.ownerId, userId);
    assert.equal(payload.generated.program_id, 'prog-success');
  }

  // Core guarantee: retries never persist a second program (the program name
  // is unique per generation — `AI Program <program_id>`).
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-success'}}), 1);
});

test('concurrent: only one request wins a key; duplicates get a predictable in_progress and no duplicate persistence', async () => {
  const body = profile('fat_loss');

  // Sequential duplicate while the first is still in flight.
  const key = `key-concurrent-${Date.now()}`;
  const first = await services.beginIdempotentGeneration(userId, key, body, {client});
  assert.equal(first.kind, 'claimed');
  assert.equal((await services.beginIdempotentGeneration(userId, key, body, {client})).kind, 'in_progress');

  // True race: two fresh begins on the same key — exactly one claim wins.
  const key2 = `key-race-${Date.now()}`;
  const results = await Promise.all([
    services.beginIdempotentGeneration(userId, key2, body, {client}),
    services.beginIdempotentGeneration(userId, key2, body, {client}),
  ]);
  const kinds = results.map((r) => r.kind).sort();
  assert.deepEqual(kinds, ['claimed', 'in_progress']);

  // Complete the winner — the duplicate never persisted anything.
  const winner = results.find((r) => r.kind === 'claimed');
  assert.ok(winner && winner.kind === 'claimed');
  await programService.persistProgramForUserWithIdempotency(
    userId,
    {program: sampleProgram('prog-race'), level: 'beginner', goal: 'fat_loss', idempotencyRecordId: winner.record.id},
    client,
  );
  // Only the winner's program exists — the racing duplicate never persisted.
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-race'}}), 1);
});

test('conflict: reusing a key with a different request body is rejected', async () => {
  const key = `key-conflict-${Date.now()}`;
  const bodyA = profile('strength');
  const bodyB = profile('fat_loss');

  const first = await services.beginIdempotentGeneration(userId, key, bodyA, {client});
  const recordId = claimedId(first);

  // Different body while in flight.
  assert.equal((await services.beginIdempotentGeneration(userId, key, bodyB, {client})).kind, 'conflict');

  // Complete the original, then: still a conflict for the wrong body…
  await programService.persistProgramForUserWithIdempotency(
    userId,
    {program: sampleProgram('prog-conflict'), level: 'beginner', goal: 'strength', idempotencyRecordId: recordId},
    client,
  );
  assert.equal((await services.beginIdempotentGeneration(userId, key, bodyB, {client})).kind, 'conflict');
  // …and a replay for the right one.
  assert.equal((await services.beginIdempotentGeneration(userId, key, bodyA, {client})).kind, 'replay');
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-conflict'}}), 1);
});

test('failed attempts can be retried with the same key as a fresh attempt', async () => {
  const key = `key-failed-${Date.now()}`;
  const body = profile('strength');

  const first = await services.beginIdempotentGeneration(userId, key, body, {client});
  const recordId = claimedId(first);

  // The route flips the record on any post-claim failure.
  await services.markIdempotentGenerationFailed(recordId, {client});

  // Retry re-claims the SAME record (fresh attempt) instead of 409/hanging.
  const retry = await services.beginIdempotentGeneration(userId, key, body, {client});
  assert.equal(retry.kind, 'claimed');
  assert.equal(claimedId(retry), recordId);
  // Nothing was persisted by the failed attempt (or its retry claim).
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-failed'}}), 0);
});

test('a stale IN_PROGRESS record (crashed holder) is reclaimable, a live one is not', async () => {
  const body = profile('fat_loss');
  const now0 = Date.now();

  // Stale: simulate a crashed request by retrying 2 minutes later with a
  // 60-second staleness window — the old IN_PROGRESS row must be reclaimable.
  const key = `key-stale-${Date.now()}`;
  const first = await services.beginIdempotentGeneration(userId, key, body, {client, now: now0, staleMs: 60_000});
  const recordId = claimedId(first);
  const second = await services.beginIdempotentGeneration(userId, key, body, {
    client,
    now: now0 + 120_000,
    staleMs: 60_000,
  });
  assert.equal(second.kind, 'claimed');
  assert.equal(claimedId(second), recordId);

  // Live: a fresh IN_PROGRESS row (real clock, default 2-minute staleness)
  // stays locked for the owner.
  const key2 = `key-live-${Date.now()}`;
  const live = await services.beginIdempotentGeneration(userId, key2, body, {client});
  assert.equal(live.kind, 'claimed');
  assert.equal((await services.beginIdempotentGeneration(userId, key2, body, {client})).kind, 'in_progress');
});
