/**
 * In-place program regeneration tests.
 *
 * Regeneration (a quiz re-completion or a preferences save, incl. rest-day
 * changes) must UPDATE the user's existing program row instead of inserting a
 * new one, so:
 *   - `WorkoutSession.programId` history stays attached to the SAME program,
 *   - no orphaned `Program` rows accumulate per user,
 *   - `QuizResponse.recommendedProgramId` / generation-ledger `programId`
 *     references keep pointing at a live program.
 *
 * Verified against a REAL scratch SQLite database (temp dir via `prisma db
 * push`, same pattern as `tests/idempotency.test.ts`):
 *   1. second persist replaces content in place (same id, restDays /
 *      sessionsPerWeek / exercise links swapped),
 *   2. completed workout sessions survive a regeneration unchanged and stay
 *      linked to the same program id,
 *   3. idempotent regeneration with a fresh key also updates the same row.
 *
 * No secrets, no real user data. Runs offline.
 */
import assert from 'node:assert/strict';
import {after, before, test} from 'node:test';
import {execFileSync} from 'node:child_process';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PrismaClient} from '@prisma/client';

import type {SaveGeneratedProgramInput} from '../src/services/programService';

// ---------------------------------------------------------------------------
// Scratch database setup
// ---------------------------------------------------------------------------

const tmpDir = mkdtempSync(join(tmpdir(), 'inplace-regeneration-test-'));
const dbUrl = `file:${join(tmpDir, 'inplace-regeneration-test.db')}`;

// Must be set BEFORE any module that constructs a PrismaClient is imported.
process.env.DATABASE_URL = dbUrl;

let client: PrismaClient;
let programService: typeof import('../src/services/programService');
let generationIdempotency: typeof import('../src/services/generationIdempotency');
let userId: string;

const WEEKDAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] as const;

before(async () => {
  const prismaCli = join(process.cwd(), 'node_modules', 'prisma', 'build', 'index.js');
  execFileSync(process.execPath, [prismaCli, 'db', 'push', '--skip-generate'], {
    env: {...process.env, DATABASE_URL: dbUrl},
    stdio: 'pipe',
    timeout: 60_000,
  });

  programService = await import('../src/services/programService');
  generationIdempotency = await import('../src/services/generationIdempotency');
  client = new PrismaClient();

  const user = await client.user.create({
    data: {
      email: `inplace-${Date.now()}@test.local`,
      name: 'In-place Tester',
      passwordHash: 'test-only',
    },
  });
  userId = user.id;
});

after(async () => {
  await client?.$disconnect();
  rmSync(tmpDir, {recursive: true, force: true});
});

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** One exercise for a given weekday (names are deterministic per weekday). */
function weekdayExercise(programId: string, weekday: string): SaveGeneratedProgramInput['program']['weekly_schedule'][number]['exercises'][number] {
  return {
    id: `ex_${programId}_${weekday}`,
    name: `Ex-${weekday}`,
    method: 'strength',
    equipment: 'dumbbell',
    sets: 3,
    reps: '8-10',
    rest_seconds: 90,
    tempo: '2-0-2',
    rpe: 7,
    instruction_cue: `Do ${weekday}.`,
    alternatives: [],
    contraindicated_for: [],
  };
}

/** A 7-session program (one per weekday) — every exercise name unique. */
function sampleProgram(programId: string): SaveGeneratedProgramInput['program'] {
  return {
    mode: 'general',
    program_id: programId,
    method_mix: {
      strength_pct: 40,
      hypertrophy_pct: 20,
      cardio_pct: 15,
      mobility_pct: 10,
      pilates_pct: 0,
      bodyweight_pct: 15,
      isometric_pct: 0,
    },
    weekly_schedule: WEEKDAYS.map((weekday, index) => ({
      day: index + 1,
      day_name: weekday,
      focus: `Focus ${weekday}`,
      warmup: [],
      exercises: [weekdayExercise(programId, weekday)],
      cooldown: [],
    })),
    progression_plan: {
      weeks_1_2: 'x',
      weeks_3_5: 'y',
      week_6: 'z',
      overload_variables: ['sets'],
    },
    warnings: [],
    notes: 'Generated by tests.',
    disclaimer: 'Test disclaimer.',
  };
}

async function linkedExerciseNames(programId: string): Promise<string[]> {
  const links = await client.programExercise.findMany({
    where: {programId},
    include: {exercise: {select: {name: true}}},
    orderBy: {order: 'asc'},
  });
  return links.map((link) => link.exercise.name);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test('regeneration replaces the user program IN PLACE — same id, no new row', async () => {
  const first = await programService.persistProgramForUser(userId, {
    program: sampleProgram('prog-v1'),
    level: 'beginner',
    goal: 'strength',
    restDays: ['monday'],
  });
  assert.equal(first.ownerId, userId);
  assert.equal(await client.program.count({where: {ownerId: userId}}), 1);
  // With restDays ['monday'], 6 of the 7 sessions carry workouts.
  assert.equal(first.sessionsPerWeek, 6);

  const second = await programService.persistProgramForUser(userId, {
    program: sampleProgram('prog-v2'),
    level: 'intermediate',
    goal: 'fat_loss',
    restDays: ['thursday', 'friday'],
  });

  // Same row, replaced content.
  assert.equal(second.id, first.id);
  assert.equal(await client.program.count({where: {ownerId: userId}}), 1);
  assert.deepEqual(second.restDays, ['thursday', 'friday']);
  assert.equal(second.sessionsPerWeek, 5);
  assert.equal(second.name, 'AI Program prog-v2');
  assert.equal(await client.program.count({where: {name: 'AI Program prog-v1'}}), 0);

  // Exercise links replaced: thursday/friday are now rest days (skipped),
  // monday is no longer a rest day (linked again).
  const names = await linkedExerciseNames(second.id);
  assert.ok(names.includes('Ex-monday'));
  assert.ok(!names.includes('Ex-thursday'));
  assert.ok(!names.includes('Ex-friday'));
  assert.equal(names.length, 5);
});

test('stored workout history stays attached across in-place regeneration', async () => {
  const program = await programService.persistProgramForUser(userId, {
    program: sampleProgram('prog-h1'),
    level: 'beginner',
    goal: 'strength',
    restDays: ['monday'],
  });
  const exercise = await client.exercise.findUniqueOrThrow({where: {name: 'Ex-monday'}});
  const session = await client.workoutSession.create({
    data: {
      userId,
      programId: program.id,
      startedAt: new Date('2026-08-01T10:00:00.000Z'),
      completedAt: new Date('2026-08-01T10:45:00.000Z'),
      durationSeconds: 2700,
      exercises: {
        create: [{exerciseId: exercise.id, order: 0, completed: true, actualSets: 3, actualReps: 10}],
      },
    },
  });

  // Regenerate with different rest days — the SAME program row is updated.
  const next = await programService.persistProgramForUser(userId, {
    program: sampleProgram('prog-h2'),
    level: 'intermediate',
    goal: 'fat_loss',
    restDays: ['friday'],
  });
  assert.equal(next.id, program.id);

  // The completed session and its performed exercises survive untouched.
  const kept = await client.workoutSession.findUniqueOrThrow({where: {id: session.id}});
  assert.equal(kept.programId, program.id);
  const keptExercises = await client.workoutSessionExercise.findMany({where: {sessionId: session.id}});
  assert.equal(keptExercises.length, 1);
  assert.equal(keptExercises[0].exerciseId, exercise.id);
  assert.equal(keptExercises[0].completed, true);

  // The program's own links were replaced with the new prescription:
  // monday is a training day again (linked), friday is the new rest day
  // (no link), and the rest-day session from the old program is gone.
  const names = await linkedExerciseNames(program.id);
  assert.ok(names.includes('Ex-monday'));
  assert.ok(!names.includes('Ex-friday'));
  assert.equal(names.length, 6); // friday is the only rest day now
});

test('idempotent regeneration with a fresh key updates the SAME program row', async () => {
  const bodyA = {level: 'beginner', goal: 'strength', equipment: ['dumbbells', 'bench'], limitations: [], limitationsDetails: ''};

  const keyA = `inplace-a-${Date.now()}`;
  const claimA = await generationIdempotency.beginIdempotentGeneration(userId, keyA, bodyA, {client});
  assert.equal(claimA.kind, 'claimed');
  if (claimA.kind !== 'claimed') return;
  const programA = await programService.persistProgramForUserWithIdempotency(
    userId,
    {program: sampleProgram('prog-i1'), level: 'beginner', goal: 'strength', restDays: ['monday'], idempotencyRecordId: claimA.record.id},
    client,
  );

  // A second, independent generation (fresh key) replaces the same row.
  const keyB = `inplace-b-${Date.now()}`;
  const bodyB = {...bodyA, goal: 'fat_loss'};
  const claimB = await generationIdempotency.beginIdempotentGeneration(userId, keyB, bodyB, {client});
  assert.equal(claimB.kind, 'claimed');
  if (claimB.kind !== 'claimed') return;
  const programB = await programService.persistProgramForUserWithIdempotency(
    userId,
    {program: sampleProgram('prog-i2'), level: 'intermediate', goal: 'fat_loss', restDays: ['friday'], idempotencyRecordId: claimB.record.id},
    client,
  );

  assert.equal(programB.id, programA.id);
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-i2'}}), 1);
  assert.equal(await client.program.count({where: {ownerId: userId, name: 'AI Program prog-i1'}}), 0);

  // Both ledger records finalized — pointing at the same (single) program.
  const recordA = await client.programGenerationRequest.findUniqueOrThrow({
    where: {userId_idempotencyKey: {userId, idempotencyKey: keyA}},
  });
  const recordB = await client.programGenerationRequest.findUniqueOrThrow({
    where: {userId_idempotencyKey: {userId, idempotencyKey: keyB}},
  });
  assert.equal(recordA.status, 'SUCCEEDED');
  assert.equal(recordA.programId, programA.id);
  assert.equal(recordB.status, 'SUCCEEDED');
  assert.equal(recordB.programId, programA.id);
});
