/**
 * Movement domain public entry point (MG-01 — Movement Graph canonical
 * schema / domain contract; MG-02 — movement taxonomy vocabulary; MG-03 —
 * source/provenance contract; MG-04 — governed ingestion pipeline; MG-05 —
 * normalization / deduplication / identity resolution).
 *
 * Exposes the Movement Graph contract types, the expressibility bridge, the
 * closed taxonomy vocabulary + FA/EN display maps, the provenance module
 * (hash contract, license rules, confidence model), the governed ingestion
 * pipeline (dry-run only), and the deterministic identity-resolution stage
 * (FA/EN normalization, S02-E-model classifier, dedup + collision report).
 * This domain is PURE and framework-independent — no Prisma, React,
 * services, or runtime side effects. Nothing in the application imports
 * this module yet (no runtime behavior change by design).
 */

export {
  MOVEMENT_GRAPH_CONTRACT_VERSION,
  type MovementCatalogVersioning,
  type MovementConfidence,
  type MovementConstraintToken,
  type MovementGraphContractVersion,
  type MovementId,
  type MovementMediaAsset,
  type MovementMediaKind,
  type MovementName,
  type MovementObject,
  type MovementPatternToken,
  type MovementProvenance,
  type MovementReference,
  type MovementRelationshipEdge,
  type MovementRelationshipKind,
  type MovementSlug,
  type MovementSourceKind,
  type MovementSymmetryToken,
  type MovementTaxonomy,
  type DifficultyTier,
  type EquipmentTypeToken,
  type HomeSuitabilityToken,
  type ImpactLevelToken,
  type LocalizedText,
  type MuscleGroupToken,
} from './types';

export { draftMovementId, movementDraftFromCatalogEntry } from './expressibility';

export {
  DIFFICULTY_TIER_DISPLAY,
  DIFFICULTY_TIERS,
  EQUIPMENT_TYPE_DISPLAY,
  EQUIPMENT_TYPES,
  HOME_SUITABILITY_DISPLAY,
  HOME_SUITABILITY_LEVELS,
  IMPACT_LEVEL_DISPLAY,
  IMPACT_LEVELS,
  MOVEMENT_CONSTRAINT_DISPLAY,
  MOVEMENT_CONSTRAINTS,
  MOVEMENT_PATTERN_DISPLAY,
  MOVEMENT_PATTERNS,
  MOVEMENT_SYMMETRIES,
  MOVEMENT_SYMMETRY_DISPLAY,
  MUSCLE_GROUP_DISPLAY,
  MUSCLE_GROUPS,
  isDifficultyTier,
  isEquipmentType,
  isHomeSuitabilityLevel,
  isImpactLevel,
  isKnownTaxonomy,
  isMovementConstraint,
  isMovementPattern,
  isMovementSymmetry,
  isMuscleGroup,
  taxonomyTokenErrors,
  toEquipmentTypeToken,
  toHomeSuitabilityToken,
  toImpactLevelToken,
  toMovementConstraintToken,
  toMovementPatternToken,
  toMovementSymmetryToken,
  toMuscleGroupToken,
  type EquipmentType,
  type HomeSuitabilityLevel,
  type ImpactLevel,
  type MovementConstraint,
  type MovementPattern,
  type MovementSymmetry,
  type MuscleGroup,
  type TaxonomyDisplay,
} from './taxonomy';

export {
  CONTENT_HASH_ALGORITHM,
  LICENSE_CLASSIFICATIONS,
  MOVEMENT_PROVENANCE_VERSION,
  UNKNOWN_LICENSE,
  classifyLicense,
  contentHashOf,
  evidenceConfidence,
  isLicenseImportable,
  isValidConfidence,
  isValidContentHash,
  isValidProvenanceRecord,
  licenseRequiresAttribution,
  recordProvenance,
  sha256Hex,
  sourceKindConfidence,
  validateProvenanceRecord,
  type ContentHash,
  type ContentHashAlgorithm,
  type LicenseCompatibility,
  type MovementProvenanceRecord,
  type ProvenanceEvidence,
  type SourceProvenanceInput,
} from './provenance';

export {
  EQUIPMENT_ALIAS_MAP,
  FREE_EXERCISE_DB_SNAPSHOT,
  LEVEL_MAP,
  MUSCLE_ALIAS_MAP,
  PATTERN_HINT_MAP,
  buildMovementObject,
  canonicalEntryJson,
  loadSnapshotDocument,
  mapEntryTaxonomy,
  parseFreeExerciseDbDocument,
  resolveIdentity,
  runIngestion,
  upstreamMovementId,
  upstreamMovementSlug,
  type BuiltMovement,
  type FreeExerciseDbEntry,
  type FreeExerciseDbSnapshot,
  type IdentityResolution,
  type IdentityStatus,
  type IngestionRunReport,
  type SourceDocument,
  type TaxonomyMapping,
} from './ingest';

export {
  buildIdentityReport,
  classifyMovementName,
  findDuplicateNames,
  fuzzySuggestions,
  hasFaScript,
  levenshteinDistance,
  normalizeFaName,
  normalizeMovementName,
  similarityScore,
  verifyIdentityReport,
  type DuplicateGroup,
  type FuzzySuggestion,
  type IdentityClass,
  type IdentityCollision,
  type IdentityReport,
  type IdentityReportRow,
  type IdentityReportVerification,
  type MovementIdentityResult,
} from './identity';